#include "../include/helper.hpp"
#include <curand_kernel.h>
#include <cuda_runtime.h>
#include <iostream>
#include <memory>
#include <cstdio>
#include <chrono>

#include "../include/p_head.hpp"
#include "../include/cache_out.hpp"
#include "../include/norm_dis.hpp"


#pragma once
extern "C" void positionalEmbeddings(float *out, int seq_len, int d_model);
extern "C" void lookup(int *x, float *embeddings, float *C, int d_model, int seq_len, int batch_size, int vocab_size);
extern "C" void addEmbeddings(float *lookedUpEmbeddings, float *sinosudialEncoding, float *C, int d_model, int seq_len, int batch_size);

class Embeddings
{

    // Positional ecnoding are fixed here generated by the sine and cosine function.
    // Token embeddings are learned in the back propagation first initillized randomly.

public:
    int d_model;
    int vocab_size;
    int seq_len;
    int batch_size;

    std::unique_ptr<Utility> utils = std::make_unique<Utility>();
    std::unique_ptr<Initializer> initilizer = std::make_unique<Initializer>();
    std::vector<std::vector<float>> tokenEmbeddings;

    // This is for debudding
    bool debug = true; // this is like s switch runs once and then turns off, now this was ment to debug by printing.

    // Initlize memory here, in a method that is frequently called is more costly.
    float *lookedUpEmbeddings = nullptr;
    float *addedEmbeddingsOut = nullptr;

    float *hostEmbeddings;

    int *deviceX;
    float *deviceEmbeddings;
    float *deviceFinalEmbeddings;
    float *lookupDeviceOut;

    float *devicePositionalEncoding;

    Embeddings(int d_model, int vocab_size, int seq_len, int batch_size, bool debug) // this batch size can very depending upon the use use
    {
        this->d_model = d_model;
        this->vocab_size = vocab_size;
        this->seq_len = seq_len;
        this->batch_size = batch_size;
        this->debug = debug;

        cudaMalloc((void **)&devicePositionalEncoding, seq_len * d_model * sizeof(float));
        positionalEmbeddings(devicePositionalEncoding, seq_len, d_model); // Let positional embedding stay on the global memory

        // this gets changed in the backpropagation
        if (debug)
        {
            // load the binary generated by torch to reduce randomness
            this->hostEmbeddings = load_bin("./src/cache/pytorch_out/token_embeddings.bin", this->vocab_size * this->d_model);

            // std::cout << "Token embedding from C++ should be the samne" << std::endl;
            // this->utils->printFlatArray2D(this->hostEmbeddings, vocab_size, d_model);

            // float *d_pe = (float *)malloc(d_model * seq_len * sizeof(float));
            // cudaMemcpy(d_pe, devicePositionalEncoding, seq_len * d_model * sizeof(float), cudaMemcpyDeviceToHost);
            // this->utils->printFlatArray2D(d_pe, seq_len, d_model);
            // free(d_pe); // 9 hr of react dev hit me forgot to free
        }
        else
        {
            this->tokenEmbeddings = initilizer->HeInit(this->vocab_size, this->d_model); // token embeddings, Shape(vocab_size, d_model)
                                                                                         // initlize fixed memory here so that our program runs faster.
            hostEmbeddings = utils->TwoDVectorToFlatMem(this->tokenEmbeddings);          // this is from I am learning so I was too scared to touch kernel
        }

        int sizeFinalEmbeddings = seq_len * d_model * batch_size * sizeof(float);
        int sizeTokenEmbeddings = seq_len * batch_size * d_model * sizeof(float);

        lookedUpEmbeddings = (float *)malloc(sizeFinalEmbeddings);
        addedEmbeddingsOut = (float *)malloc(sizeFinalEmbeddings); // this is the out.

        // copy to GPU memory
        // copy embeddings to the GPU after making int flat
        cudaMalloc((void **)&deviceEmbeddings, vocab_size * d_model * sizeof(float));
        cudaMemcpy(deviceEmbeddings, hostEmbeddings, vocab_size * d_model * sizeof(float), cudaMemcpyHostToDevice);

        // allocare GPU memory for final embeddings
        cudaMalloc((void **)&deviceFinalEmbeddings, seq_len * d_model * batch_size * sizeof(float));
        // allocate memory for output after lookup Shape(seq_len, batch_size, d_model)
        cudaMalloc((void **)&lookupDeviceOut, seq_len * batch_size * d_model * sizeof(float));

        cudaMalloc((void **)&deviceX, seq_len * batch_size * sizeof(int));
    };

    ~Embeddings()
    {
        (lookedUpEmbeddings != nullptr ? free(lookedUpEmbeddings) : void());
        (addedEmbeddingsOut != nullptr ? free(addedEmbeddingsOut) : void());

        delete[] hostEmbeddings;

        cudaFree(deviceX);
        cudaFree(deviceEmbeddings);
        cudaFree(deviceFinalEmbeddings);

        cudaFree(devicePositionalEncoding);
        cudaFree(lookupDeviceOut);
    }

    float *forward(Batch currentBatch)
    {
        // THIS SIZE MIGHT CHANGE ACCORDING TO THE DROP LAST PARAMATER AND WE NEED TO KEEP TRACK OF THIS.
        int actual_batch = currentBatch.width;
        // that x is deleted when the dataloader is destroyed.
        int *hostX = currentBatch.x;
        // copy this to GPU
        cudaMemcpy(deviceX, hostX, seq_len * actual_batch * sizeof(int), cudaMemcpyHostToDevice);
        lookup(deviceX, deviceEmbeddings, lookupDeviceOut, d_model, seq_len, actual_batch, vocab_size); // actual batch because the batch size may vary here
        // Now this result gets added
        addEmbeddings(lookupDeviceOut, devicePositionalEncoding, deviceFinalEmbeddings, d_model, seq_len, actual_batch);

        cudaMemcpy(addedEmbeddingsOut, deviceFinalEmbeddings, actual_batch * seq_len * d_model * sizeof(float), cudaMemcpyDeviceToHost);

        // if (debug)
        // {
        //     std::cout << " Added embeddings from embedding method " << std::endl;
        //     this->utils->printFlatArray3D(addedEmbeddingsOut, actual_batch, seq_len, d_model);
        // }

        if (debug)
        {
            // lets release that x from C++, this happens once
            // but we must release it because python needs that.

            releaseFile( // 1 item of a batch
                "x.bin",
                hostX,
                actual_batch * seq_len);

            // release net embeddings to a binary file
            releaseFile(
                "embedding.bin",
                addedEmbeddingsOut,
                actual_batch * seq_len * d_model);
        }

        debug = false;
        return addedEmbeddingsOut;
    }

    float *getEmbeddingsParamaters()
    {
        return this->hostEmbeddings;
    }
};