#+title: Learning parallel computing and c++

* Learning how to add vectors in Kernel

This is my first cuda Kernel. The __global__ keyword means it runs on the GPU. Each thread handles one element.


** Understanding of thead block and GPU Hardware

GPU unlike CPU has thousands of smaller cores which I understand from my childhood questoning why does my laptop with igpu wont render complex graphics.

** Understanding how are those threads organized for NVIDA GPU
NVIDA organizes threads in a hierarchy

Grid (entire kernel launch)
        - Blocks (groups of theads)
        - Threads (individual workers)



#+BEGIN_SRC  C

__global__ void add(int *a, int *b, int *c, int N) {
   int i = blockIdx.x * blockDim.x + theadIdx.x;
   if (i < N) {
     c[i] = a[i] + b[i];
   }
}

#+END_SRC

**** Let's understand what's happenning here
- blockIdx.x -> which block this thread is in
- theadIdx.x -> which thread within the block
- i -> the unique index for this thread across all blocks
- if (i < N) -> making sure we don't go out of bounds

#+BEGIN_SRC  C
__global__ void add(int *a, int *b, int * c, int N)
#+END_SRC

- Those pointers in the paramater points to the GPU memory not CPU
