#+title: Learning parallel computing and c++

*** Understanding of thead block and GPU Hardware

GPU unlike CPU has thousands of smaller cores which I understand from my childhood questoning why does my laptop with igpu wont render complex graphics.

*** Kernels
A function that runs on the GPU

*** When we lanch a kernels they are executed as a set of parallel threads

The smallest unit of execution. One thread = one execution of your kernel. It has its own registers (private variables), stack, and unique id (theadIdx)

When we write something like launch 256 threads.
GPU sees: 8 wraps of 32

*** Block

A group of threads that we define at launch. Threads in the same block can share fast memory. Threads in different blocks cannot communicate.

#+BEGIN_SRC C

add<<4, 256>> // 4 blocks, 256 threads per block
  // we have 4 blocks and each with 256 threads running in parallel.

  // the second arguement 256 is our block size
#+END_SRC

#+RESULTS:

*** Grid
All the blocks in a single thread kernel launch. The entire army of theads. They all share global memory.

Grid

Block 0 (256 threads = 8 wraps) ...

*** Understanding how are those threads organized for NVIDA GPU
NVIDA organizes threads in a hierarchy

Grid (entire kernel launch)
        - Blocks (groups of theads)
        - Threads (individual workers)



#+BEGIN_SRC  C

__global__ void add(int *a, int *b, int *c, int N) {
   int i = blockIdx.x * blockDim.x + theadIdx.x;
   if (i < N) {
     c[i] = a[i] + b[i];
   }
}

#+END_SRC

**** Let's understand what's happenning here
- blockIdx.x -> which block this thread is in
- theadIdx.x -> which thread within the block
- i -> the unique index for this thread across all blocks
- if (i < N) -> making sure we don't go out of bounds

#+BEGIN_SRC  C
__global__ void add(int *a, int *b, int * c, int N)
#+END_SRC

- Those pointers in the paramater points to the GPU memory not CPU
*** Exchanging data
When we exchange data from GPU to CPU it gets travelled from the PCIE express BUS which makes the cost of exchanging slower.
*** Organizing threads
CUDA organizes theads in a 3-level hierarchy: Threads blocks grid
- Threads within a block run on the same Stremaing Multiprocressor(SM) which is why shared memeory is fast and sync is possible.
- Grid can scale according to all block size.
- A group of 32 threads called wrap is the actual hardware execution unit, all threads in a wrap execute the same instruction in lockstep.
- If threads from different blocks communicuate then they need Dynamic Random Access Memory to communicate which makes it slower.

*** Good CUDA code
- Load data from global memory into shared memeory once.
- Do all the heavy computation using shared memory.
- Write resules back to global memory at the end.
*** Understanding the execution of smile kernel
Each thread computes a unique i based on where it sits.
For example:-
Block 0: threads indices form 0-256
Block 1: threads handle indices from 256-511
If we have comething like add <<4, 256>>

What happens in parallel c[i] = a[i] + b[i] simultaneously in paralle. No thread is going to wait for another.
For example thread 0 adds a[0] + b[0]
Thread 1 adds a[1] + b[1]

For example on a cpu
#+BEGIN_SRC C
for (int i = 0; i < N; i++) {
  c[i] = a[i] + b[i]
 }
#+END_SRC

#+RESULTS:

if (i < N) protects if our array size does not divide evenly into blocks.

if N is the size of array in our case adding element from an array then it is divided into blocks and threads.

CUDA grid can hold up to 2^31-1 blocks per dimension, so we can launch huge numbers of blocks but the problem is GPU might not have enough SM to execute those.

Let's see how the hardware runs blocks in waves.

Wave 1 first Nblocks run on all SM's
wave 2 next N block so on and so on until done.

*** Allocation of grid size.

Normally if we just did
#+BEGIN_SRC C
int gridSize = N / blockSize; // This is a floor division
#+END_SRC

N = 1000, blockSize=256 = 1000/256 = 3 floor
3x256 threads = 768 threads
missing 232 elements.
#+BEGIN_SRC C
int girdSize = (N + blockSize - 1) / blockSize;
#+END_SRC

N = 1000, blockSize = 256
(1000 + 255) / 256
= 1255 / 256 = 4 blocks  = 4x256=1024 threads

Why do we calculate the gird size instead of allocating it ourself?
Well, because the N might be extremly large, it might come from a database so we want to make it according to N.
*** We have a code that does the softmax actication

#+BEGIN_SRC C
__global__ void softmax(float *arr, float *out, size_t N)
{
    __shared__ float total_sum; 

    int i = blockDim.x * blockIdx.x + threadIdx.x;

    if (threadIdx.x == 0) {
        total_sum = 0.0f; 
    }
    __syncthreads(); 

    if (i < N) {
        atomicAdd(&total_sum, expf(arr[i]));
    }

    __syncthreads();

    if (i < N) {
        out[i] = expf(arr[i]) / total_sum;
    }
}

#+END_SRC
*** Let's understand this code line by line
First of all we have shared float called total_sum
And we initiallize that by zero at first.

Then we call the
#+BEGIN_SRC C
__syncthreads();
#+END_SRC

#+RESULTS:

Which is going to wait for all the threads to catch up
After that we do the lower part of the softmax function

#+BEGIN_SRC C
atomicAdd(&total_sum, expf(arr[i]));
#+END_SRC

And we again wait for the thread to sync.

*** What happens if we do not wait for the thread of sync.
We will introduce a bug known as Race condition

GPU threads are known to execute at different speeds, they will read and write to the shared total_sum variable completely out of order.

If the order does not matter then it's fine not to sync but in our case in diving in softmax the order matters.

#+BEGIN_SRC
total_sum
#+END_SRC
*** Understanding atomicAdd in parallel computing.

atomicAdd is a speciallized hardware instruction that guarantees a read modify write opreation on a variable is completed by a single thread without any interference from other threads.

It basically forces threads competing for the same memory address to wait for their turn preventing them from stepping on each other's toes and corrupting data.

*** Understanding the problem
#+BEGIN_SRC
Memory (sum = 10)

Thread A -> reads 10 from memory -> modifies (10 + 5 = 15) -> writes 15 back to memory

Thread B => reads 10 from memory -> modifies (10 + 3 = 13) -> writes 13 back to memory

#+END_SRC

The atomicAdd() fixes that by locking the memory address in the GPU for duration of those three steps (Read, Modify, and Write)

*** If thread A, and thread B is executing how will thread B access memory of the variable sum?

This effect is called hardware stalling. The thread B will wait at the memory gateway ultil thread A reseases the lock.

*** Understanding of memory allocation
In different programming languages the memory can be allocated on either a stack or a heap.

We can think of stack as fast organized but limited, and heap like a giant pool of storage which requires effort to find things.
Stack allocation is managed by the CPU and Heap allocation is managed by the programmer or if the language has GC then GC will take care of it.

The stack is just a slice of computers system RAM. The CPU uses the stack pointer to quickly push and pop data in a LIFO.

*** Problem to solve, Positional encoding like in the original attention papaer, Learning to think in the hardware level.

When calculating the positional encoding for a particular sequence we have a conditional branch, if the index is even then we calculate the sin and when calculating the odd position we go for cos.

Because we have adjacent threads like thread 0 and thread 1. We will trigger something called wrap divergence. This occours when thread whithin the same wrap follow different execution like if-else.

Inside of a warp which has 32 threads our code get's assign to multiple threads.
Let's take an example of an array which some elements and we want to increment each element by 2.0f. All those things happen in parallel.

What is the size of an array is greater than the number of thread itself.

*** Thinking in GPU level

CUDA gives each thread two built in coordinates blockIdx and threadIdx. blockIdx belongs to in the grid and threadIdx position withing that grid. By combination of both each thread computes a unqiue (row, col) pair that's it's address in the output matrix.

#+BEGIN_SRC C
// A simple nested loop

for (int i = 0; i < 4; i++)
  for (int j = 0; j < 4; j++)
    // we are here work(i, j);
    // we can think of this as time being our axis.

#+END_SRC
*** Working with GPU
#+BEGIN_SRC C
int i = blockIdx.y * blockDim.y + threadIdx.y;
int j = blockIdx.x * blockDim.x + threadIdx.x;


#+END_SRC

Becase things are happenning in the parallel we need to think in that way.

**** Positional encoding in parallel

#+BEGIN_SRC C++

__global__ void positional_embedding_kernel(float *out, int seq_len, int d_model)
  {
    int pos = blockIdx.y * blockDim.y + threadIdx.y;
    int k = blockIdx.x * blockDim.x + threadIdx.x;

    if (pos >= seq_len || k >= d_model)
      return;

    int  i = k / 2;
    float denom = powf(10000.0f, 2 * i / d_model);

    float sin_val, cos_val;
    sincosf(pos/denom, &sin_val, &cos_val);
    out[pos * d_model + k] = (k % 2 == 0) ? sin_val : cos_val;
  }

#+END_SRC

We are calculating both sin and cos to prevent branching divergence in the threads.

**** Launching a kernel for the above code

#+BEGIN_SRC  C

void positionalEmbeddings(float *out, int seq_len, int d_model)
  {
    dim3 block(16, 16) // just 256 threads 2d block

   dim3 grid(
     (d_model + 15) / 16,
     (seq_len + 15) / 16
   )

      positional_embedding_kernel<<grid, block>>(out, seq_len, d_model);

    cudaDeviceSynchronize();
  }

#+END_SRC

For the grid we have same idea, grids are just collection of blocks.

okay so let us assume we have d_model = 512 and seq_len = 40

grid.x = (512 + 15) / 16 = 32 // 32 tiles needed horizontally
grid.y = (40 + 15) / 16 = 3 // tiles needed vertically


so in one block we have 16x16 = 256 threads
and according to our eqiation we have around 32x3 grid
so number of threads will be 96x256 = 24756

(N+15)/16 ensures we never under cover.

+15 brings up any-non multiple just enough to round up.

The celling division guarantees that the grid dimension covers all the data.

(N + 16) / 16 always ensures to round up the full data like in our case.

If we assume block(A,B) in a 2d kernel launch then,
we can say that grid (total_cols + A - 1) / A
(total_rows + B - 1) / B
this ensures we have full data coverrage. Data coverage means every element inside of our matrix has assigned thread to it.
