#+title: Learning parallel computing and c++

*** Understanding of thead block and GPU Hardware

GPU unlike CPU has thousands of smaller cores which I understand from my childhood questoning why does my laptop with igpu wont render complex graphics.

*** Kernels
A function that runs on the GPU

*** When we lanch a kernels they are executed as a set of parallel threads

The smallest unit of execution. One thread = one execution of your kernel. It has its own registers (private variables), stack, and unique id (theadIdx)

When we write something like launch 256 threads.
GPU sees: 8 wraps of 32

*** Block

A group of threads that we define at launch. Threads in the same block can share fast memory. Threads in different blocks cannot communicate.

#+BEGIN_SRC C

add<<4, 256>> // 4 blocks, 256 threads per block
  // we have 4 blocks and each with 256 threads running in parallel.

  // the second arguement 256 is our block size
#+END_SRC

#+RESULTS:

*** Grid
All the blocks in a single thread kernel launch. The entire army of theads. They all share global memory.

Grid

Block 0 (256 threads = 8 wraps) ...

*** Understanding how are those threads organized for NVIDA GPU
NVIDA organizes threads in a hierarchy

Grid (entire kernel launch)
        - Blocks (groups of theads)
        - Threads (individual workers)



#+BEGIN_SRC  C

__global__ void add(int *a, int *b, int *c, int N) {
   int i = blockIdx.x * blockDim.x + theadIdx.x;
   if (i < N) {
     c[i] = a[i] + b[i];
   }
}

#+END_SRC

**** Let's understand what's happenning here
- blockIdx.x -> which block this thread is in
- theadIdx.x -> which thread within the block
- i -> the unique index for this thread across all blocks
- if (i < N) -> making sure we don't go out of bounds

#+BEGIN_SRC  C
__global__ void add(int *a, int *b, int * c, int N)
#+END_SRC

- Those pointers in the paramater points to the GPU memory not CPU
*** Exchanging data
When we exchange data from GPU to CPU it gets travelled from the PCIE express BUS which makes the cost of exchanging slower.
*** Organizing threads
CUDA organizes theads in a 3-level hierarchy: Threads blocks grid
- Threads within a block run on the same Stremaing Multiprocressor(SM) which is why shared memeory is fast and sync is possible.
- Grid can scale according to all block size.
- A group of 32 threads called wrap is the actual hardware execution unit, all threads in a wrap execute the same instruction in lockstep.
- If threads from different blocks communicuate then they need Dynamic Random Access Memory to communicate which makes it slower.

*** Good CUDA code
- Load data from global memory into shared memeory once.
- Do all the heavy computation using shared memory.
- Write resules back to global memory at the end.
*** Understanding the execution of smile kernel
Each thread computes a unique i based on where it sits.
For example:-
Block 0: threads indices form 0-256
Block 1: threads handle indices from 256-511
If we have comething like add <<4, 256>>

What happens in parallel c[i] = a[i] + b[i] simultaneously in paralle. No thread is going to wait for another.
For example thread 0 adds a[0] + b[0]
Thread 1 adds a[1] + b[1]

For example on a cpu
#+BEGIN_SRC C
for (int i = 0; i < N; i++) {
  c[i] = a[i] + b[i]
 }
#+END_SRC

#+RESULTS:
