
* Understanding of the embeddings inside the Transformer

** Token embeddings:
Token embeddings are of shape [vocab_size, d_model]. They are randomly initialized at first and learned during the training process. We can imagine the embedding matrix as a high-dimensional vector space that contains all the vocabulary we want the model to learn from.

** Positional encoding:
Taking the original Transformer as an example, it used sinusoidal positional encoding, which was fixed during training. The position is determined by sine and cosine functions according to the position index, storing them in a higher-dimensional space.

** Final embeddings

#+BEGIN_SRC Python

# Positional encoding

H = [... d_model]
E = [... d_model]
L = [... d_model]
L = [... d_model]
O = [... d_model]

Shape(seq_len, d_model)

#+END_SRC

#+BEGIN_SRC Python

# Token embeddings (all of the voab)

a = [...d_model]
...
z = [...d_model]

Shape(vocab_size, d_model)
#+END_SRC

They are randomly initilized at first and adjusted during the training procress.

The final embeddings are added together. First of all lets think of the token encoding as a large lookup table.

"the" = ID 547 (these are encoded based on position or whatever)
"cat" = ID 8923
"sat" = ID 4291

**** Token embedding matrix

#+BEGIN_SRC Python
Row 547 [.... d_model] "the"
Row 8923 [.... d_model] "cat"
Row 4291 [.... d_model] "sat"

#+END_SRC

**** Token embeddings for the sequence stacked in the order
#+BEGIN_SRC Python
E = [
    [.... ] position 0: "the"
            position 1: "cat"
            position 2: "sat"
]
Shape (3, 4)
#+END_SRC

**** Positional encoding

#+BEGIN_SRC Python
P = [
   [.... ] # position 0 encoding
                 ....
]
#+END_SRC

Now add those two E[0] P[0] ...

**** We need to understand the batch and sequeces here first

We can think of batch_size as how many times the things are procressed in parallel horizontal and seq_len as the items sequence vertical.


#+BEGIN_SRC Python
[....]
[....]
[....]
[....] # Shape (seq_len, batch_size) example (4, 32)
#+END_SRC

So at once if the batch_size = 32 then we have 32 element working in parallel for efficient computation.

#+BEGIN_SRC Python
# Example we have batch 0:
indices grabbled: [0, 1, 2, .... 31]

item0 item1 item2 item3 item..31
t0
t1
t2
..
tn


#+END_SRC

*** Understanding the loop up mechanism better with the input x

In our input x we have the two dimensional matrix, keeping it two dimensional for simpliity while trading off little bit of efficiency.

#+BEGIN_SRC Python

x = [
    ....
    ....
] # in column we have ids, seq_len x batch_size
#+END_SRC

**** Lets look at the embedding loopup table

#+BEGIN_SRC Python
emb = [
    .... row 1
    .... row n
] # dimension is vocab_size x d_model
#+END_SRC

So we basically look at row from emb vector from the col of x

** Lets learn how does this work in GPU Kernel.

#+BEGIN_SRC C
__global__ void finalEmbeddings(
    float *x,
    float *embeddings,
    float *encoding,
    float *finalEmbeddings,
    int d_model,
    int seq_len,
    int vocab_size,
    int batch_size
)
{

    int rows = blockIdx.y * blockDim.y + threadIdx.y; // rows
    int cols = blockIdx.x * blockDim.x + threadIdx.x; // cols


    if (!(rows < seq_len && cols < batch_size))
        return;

    int index_x = rows * batch_size + cols;

}
#+END_SRC

For x our shape is (seq_len x batch_size). I like to imagine this as hanging tokens in the batch rope.

Lets imagine a case in the above code.

we have a data grid of x of lets say.

#+BEGIN_SRC Python

x shape = (seq_len, batch_size) = (16, 32)

        col0   col1   col2  ...  col31
       ┌─────┬──────┬──────┬─────┬──────┐
t0     │ 798 │  814 │  830 │ ... │  496 │
t1     │ 799 │  815 │  831 │ ... │  497 │
t2     │ 800 │  816 │  832 │ ... │  498 │
...    │ ... │  ... │  ... │ ... │  ... │
t15    │ 813 │  829 │  845 │ ... │  511 │
       └─────┴──────┴──────┴─────┴──────┘
#+END_SRC

And for our rows and cols our position is (1, 1)

#+BEGIN_SRC C
int index_x = rows * batch_size + cols;

// we have row = 1, cols = 1 then it will map to 1 * 31 + 1 = 32
#+END_SRC

How is the location assigned? Important to understand here. Its assigned like a periodic table here. so that formula will help us land in that position. Everything else is happenning in parallel.

#+BEGIN_SRC Python
Row 0:   (0,0)=0   (0,1)=1   (0,2)=2   ... (0,31)=31
Row 1:   (1,0)=32  (1,1)=33  (1,2)=34  ... (1,31)=63
#+END_SRC
