
* Understanding of the embeddings inside the Transformer

** Token embeddings:
Token embeddings are of shape [vocab_size, d_model]. They are randomly initialized at first and learned during the training process. We can imagine the embedding matrix as a high-dimensional vector space that contains all the vocabulary we want the model to learn from.

** Positional encoding:
Taking the original Transformer as an example, it used sinusoidal positional encoding, which was fixed during training. The position is determined by sine and cosine functions according to the position index, storing them in a higher-dimensional space.

** Final embeddings

#+BEGIN_SRC Python

# Positional encoding

H = [... d_model]
E = [... d_model]
L = [... d_model]
L = [... d_model]
O = [... d_model]

Shape(seq_len, d_model)

#+END_SRC

#+BEGIN_SRC Python

# Token embeddings (all of the voab)

a = [...d_model]
...
z = [...d_model]

Shape(vocab_size, d_model)
#+END_SRC

They are randomly initilized at first and adjusted during the training procress.

The final embeddings are added together. First of all lets think of the token encoding as a large lookup table.

"the" = ID 547 (these are encoded based on position or whatever)
"cat" = ID 8923
"sat" = ID 4291

**** Token embedding matrix

#+BEGIN_SRC Python
Row 547 [.... d_model] "the"
Row 8923 [.... d_model] "cat"
Row 4291 [.... d_model] "sat"

#+END_SRC

**** Token embeddings for the sequence stacked in the order
#+BEGIN_SRC Python
E = [
    [.... ] position 0: "the"
            position 1: "cat"
            position 2: "sat"
]
Shape (3, 4)
#+END_SRC

**** Positional encoding

#+BEGIN_SRC Python
P = [
   [.... ] # position 0 encoding
                 ....
]
#+END_SRC

Now add those two E[0] P[0] ...

**** We need to understand the batch and sequeces here first

We can think of batch_size as how many times the things are procressed in parallel horizontal and seq_len as the items sequence vertical.


#+BEGIN_SRC Python
[....]
[....]
[....]
[....] # Shape (seq_len, batch_size) example (4, 32)
#+END_SRC

So at once if the batch_size = 32 then we have 32 element working in parallel for efficient computation.

#+BEGIN_SRC Python
# Example we have batch 0:
indices grabbled: [0, 1, 2, .... 31]

item0 item1 item2 item3 item..31
t0
t1
t2
..
tn


#+END_SRC

*** Understanding the loop up mechanism better with the input x

In our input x we have the two dimensional matrix, keeping it two dimensional for simpliity while trading off little bit of efficiency.

#+BEGIN_SRC Python

x = [
    ....
    ....
] # in column we have ids, seq_len x batch_size
#+END_SRC

**** Lets look at the embedding loopup table

#+BEGIN_SRC Python
emb = [
    .... row 1
    .... row n
] # dimension is vocab_size x d_model
#+END_SRC

So we basically look at row from emb vector from the col of x

** Lets learn how does this work in GPU Kernel.

#+BEGIN_SRC Python

x shape = (seq_len, batch_size) = (16, 32)

        col0   col1   col2  ...  col31
       ┌─────┬──────┬──────┬─────┬──────┐
t0     │ 798 │  814 │  830 │ ... │  496 │
t1     │ 799 │  815 │  831 │ ... │  497 │
t2     │ 800 │  816 │  832 │ ... │  498 │
...    │ ... │  ... │  ... │ ... │  ... │
t15    │ 813 │  829 │  845 │ ... │  511 │
       └─────┴──────┴──────┴─────┴──────┘
#+END_SRC

And for our rows and cols our position is (1, 1)

*** Understanding the execution of our code in the Kernel

#+BEGIN_SRC C
__global__ void kernel(float *A, float *B, float *C)
{
    int row = blockIdx.x;
    int col = blockIdx.y;

    int index = (row * 3) + col;
    float val = A[index];

    int threadIx = threadIdx.x;

    printf("Rows: %d Cols: %d ThreadIx: %d value %.1f \n", row, col, threadIx, val);
}

int main()
{
    float A[9] = {
        0, 1, 2,
        3, 4, 5,
        6, 7, 8};

    float B[9] = {0};
    float C[9];

    /*
      A = {
        {1, 2, 3},
        {4, 5, 6},
        {7, 8, 9}
    } smilialry for B

    ,*/

    float *device_arr_A, *device_arr_B, *device_arr_C;
    cudaMalloc((void **)&device_arr_A, 9 * sizeof(float));
    cudaMalloc((void **)&device_arr_B, 9 * sizeof(float));
    cudaMalloc((void **)&device_arr_C, 9 * sizeof(float));


    cudaMemcpy(device_arr_A, A, 9 * sizeof(float), cudaMemcpyHostToDevice);
    cudaMemcpy(device_arr_B, B, 9 * sizeof(float), cudaMemcpyHostToDevice);
    cudaMemcpy(device_arr_C, C, 9 * sizeof(float), cudaMemcpyHostToDevice);


    dim3 grid(3, 3);
    dim3 block(1);


    kernel<<<grid, block>>>(device_arr_A, device_arr_B, device_arr_C);

    cudaDeviceSynchronize();
    cudaMemcpy(device_arr_C, C, 9 * sizeof(float), cudaMemcpyDeviceToHost);

    cudaFree(device_arr_A);
    cudaFree(device_arr_B);
    cudaFree(device_arr_C);
}
#+END_SRC

In our Kernel launch above we have 3x3 grid with each having one thread to compute that perfectly covers our array. And will be easy for us to think of.

Now lets visualize the formula

#+BEGIN_SRC C
int index = (row * 3) + col;
float val = A[index];
#+END_SRC

#+BEGIN_SRC Python

At Pos(0, 0)

int index = 0*3 + 0 = 0
val = A[0] = 1

At Pos(0, 1)
int index = 0*3 + 1 = 1
A[1] = 2 # This is a flat strip of memory

At Pos(0, 2)
int index = 0*3 + 2 = 2
A[2] = 3

#+END_SRC



**** Understanding the boundary check in the cuda kernel

Here we have more than 1 thread that is overkilled, we can notive that we have multiple zero's which is reading the garbage data.

#+BEGIN_SRC Bash
Rows: 0 Cols: 4 ThreadIx: 0 value 4.0
Rows: 0 Cols: 5 ThreadIx: 1 value 5.0
Rows: 1 Cols: 2 ThreadIx: 0 value 5.0
Rows: 1 Cols: 3 ThreadIx: 1 value 6.0
Rows: 0 Cols: 0 ThreadIx: 0 value 0.0
Rows: 0 Cols: 1 ThreadIx: 1 value 1.0
Rows: 2 Cols: 0 ThreadIx: 0 value 6.0
Rows: 2 Cols: 1 ThreadIx: 1 value 7.0
Rows: 1 Cols: 0 ThreadIx: 0 value 3.0
Rows: 1 Cols: 1 ThreadIx: 1 value 4.0
Rows: 2 Cols: 4 ThreadIx: 0 value 0.0
Rows: 2 Cols: 5 ThreadIx: 1 value 0.0
Rows: 1 Cols: 4 ThreadIx: 0 value 7.0
Rows: 1 Cols: 5 ThreadIx: 1 value 8.0
Rows: 2 Cols: 2 ThreadIx: 0 value 8.0
Rows: 2 Cols: 3 ThreadIx: 1 value 0.0
Rows: 0 Cols: 2 ThreadIx: 0 value 2.0
Rows: 0 Cols: 3 ThreadIx: 1 value 3.0
#+END_SRC

After implementing the bounday check

#+BEGIN_SRC C
if (!(rows < 3 &&  cols < 3)) return;

/*
Rows: 1 Cols: 2 ThreadIx: 0 value 5.0
Rows: 0 Cols: 2 ThreadIx: 0 value 2.0
Rows: 2 Cols: 2 ThreadIx: 0 value 8.0
Rows: 2 Cols: 0 ThreadIx: 0 value 6.0
Rows: 2 Cols: 1 ThreadIx: 1 value 7.0
Rows: 0 Cols: 0 ThreadIx: 0 value 0.0
Rows: 0 Cols: 1 ThreadIx: 1 value 1.0
Rows: 1 Cols: 0 ThreadIx: 0 value 3.0
Rows: 1 Cols: 1 ThreadIx: 1 value 4.0

We have the clean output.
,*/
#+END_SRC

#+RESULTS:


Before creating a lookup table lets see whats going on here

#+BEGIN_SRC C
__global__ void kernel(int *A, float *B, float *C)
{
    int rows = blockIdx.y * blockDim.y + threadIdx.y;
    int cols = blockIdx.x * blockDim.x + threadIdx.x;
    int e = threadIdx.x;

    if (!(rows < 3 && cols < 3))
        return;

    int index = (rows * 3) + cols;
    int val = A[index];

    int indexB = (val * 6) + e;
    float valB = B[indexB];

    int threadIx = threadIdx.x;

    printf("Rows: %d Cols: %d ThreadIx: %d value %d valB %.1f \n", rows, cols, threadIx, val, valB);
}
/*
Rows: 1 Cols: 2 ThreadIx: 0 value 0 valB 1.0
Rows: 2 Cols: 0 ThreadIx: 0 value 1 valB 7.0
Rows: 2 Cols: 1 ThreadIx: 1 value 2 valB 14.0
Rows: 0 Cols: 0 ThreadIx: 0 value 0 valB 1.0
Rows: 0 Cols: 1 ThreadIx: 1 value 1 valB 8.0
Rows: 1 Cols: 0 ThreadIx: 0 value 2 valB 13.0
Rows: 1 Cols: 1 ThreadIx: 1 value 1 valB 8.0
Rows: 0 Cols: 2 ThreadIx: 0 value 2 valB 13.0
Rows: 2 Cols: 2 ThreadIx: 0 value 1 valB 7.0
*/
#+END_SRC

Here in the above example we are just looking at that the first values of the row.

Now How do we insrt in a flat array by rows and cols.

#+BEGIN_SRC C

int A[9] = {
      0, 1, 2,
      2, 1, 0,
      1, 2, 1};

// {0, 1, 2, 2, 1, 0, 1, 2, 1} This is the flat array
#+END_SRC

We have index = (r * width) + c

lets say we want to insert as (0, 1)

index = (0 * 3) + 1 = index 1 on a commented array and so on and so forth.
