
* Understanding of the embeddings inside the Transformer

** Token embeddings:
Token embeddings are of shape [vocab_size, d_model]. They are randomly initialized at first and learned during the training process. We can imagine the embedding matrix as a high-dimensional vector space that contains all the vocabulary we want the model to learn from.

** Positional encoding:
Taking the original Transformer as an example, it used sinusoidal positional encoding, which was fixed during training. The position is determined by sine and cosine functions according to the position index, storing them in a higher-dimensional space.

** Final embeddings

#+BEGIN_SRC Python

# Positional encoding

H = [... d_model]
E = [... d_model]
L = [... d_model]
L = [... d_model]
O = [... d_model]

Shape(seq_len, d_model)

#+END_SRC

#+BEGIN_SRC Python

# Token embeddings (all of the voab)

a = [...d_model]
...
z = [...d_model]

Shape(vocab_size, d_model)
#+END_SRC

They are randomly initilized at first and adjusted during the training procress.

The final embeddings are added together. First of all lets think of the token encoding as a large lookup table.

"the" = ID 547 (these are encoded based on position or whatever)
"cat" = ID 8923
"sat" = ID 4291

**** Token embedding matrix

#+BEGIN_SRC Python
Row 547 [.... d_model] "the"
Row 8923 [.... d_model] "cat"
Row 4291 [.... d_model] "sat"

#+END_SRC

**** Token embeddings for the sequence stacked in the order
#+BEGIN_SRC Python
E = [
    [.... ] position 0: "the"
            position 1: "cat"
            position 2: "sat"
]
Shape (3, 4)
#+END_SRC

**** Positional encoding

#+BEGIN_SRC Python
P = [
   [.... ] # position 0 encoding
                 ....
]
#+END_SRC

Now add those two E[0] P[0] ...

**** We need to understand the batch and sequeces here first

We can think of batch_size as how many times the things are procressed in parallel horizontal and seq_len as the items sequence vertical.


#+BEGIN_SRC Python
[....]
[....]
[....]
[....] # Shape (seq_len, batch_size) example (4, 32)
#+END_SRC

So at once if the batch_size = 32 then we have 32 element working in parallel for efficient computation.

#+BEGIN_SRC Python
# Example we have batch 0:
indices grabbled: [0, 1, 2, .... 31]

item0 item1 item2 item3 item..31
t0
t1
t2
..
tn


#+END_SRC

*** Understanding the loop up mechanism better with the input x

In our input x we have the two dimensional matrix, keeping it two dimensional for simpliity while trading off little bit of efficiency.

#+BEGIN_SRC Python

x = [
    ....
    ....
] # in column we have ids, seq_len x batch_size
#+END_SRC

**** Lets look at the embedding loopup table

#+BEGIN_SRC Python
emb = [
    .... row 1
    .... row n
] # dimension is vocab_size x d_model
#+END_SRC

So we basically look at row from emb vector from the col of x

** Lets learn how does this work in GPU Kernel.

#+BEGIN_SRC Python

x shape = (seq_len, batch_size) = (16, 32)

        col0   col1   col2  ...  col31
       ┌─────┬──────┬──────┬─────┬──────┐
t0     │ 798 │  814 │  830 │ ... │  496 │
t1     │ 799 │  815 │  831 │ ... │  497 │
t2     │ 800 │  816 │  832 │ ... │  498 │
...    │ ... │  ... │  ... │ ... │  ... │
t15    │ 813 │  829 │  845 │ ... │  511 │
       └─────┴──────┴──────┴─────┴──────┘
#+END_SRC

And for our rows and cols our position is (1, 1)

*** Understanding the execution of our code in the Kernel

#+BEGIN_SRC C
__global__ void kernel(int *A, float *B, float *C, int embedding)
{
    int rows = blockIdx.y;
    int cols = blockIdx.x;
    int e = threadIdx.x;

    int index = (rows * 3) + cols;
    int val = A[index];

    int indexB = (val * 6) + e;
    float valB = B[indexB];

    C[rows * gridDim.x * embedding + cols * embedding + e] = valB;
    /*

    rows * gridDim.x * embeddings
    skip row, each one of them has 3 position and final embeddings have 15 values.

    + how for how many cols to skip cols * embeddings + threadId

    */
}

int main()
{
    int A[9] = {
        0, 1, 2,
        2, 1, 0,
        1, 2, 1};

    float B[36] = {
        1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f,
        7.0f, 8.0f, 9.0f, 10.0f, 11.0f, 12.0f,
        13.0f, 14.0f, 15.0f, 16.0f, 17.0f, 18.0f,
        19.0f, 20.0f, 21.0f, 22.0f, 23.0f, 24.0f,
        25.0f, 26.0f, 27.0f, 28.0f, 29.0f, 30.0f,
        31.0f, 32.0f, 33.0f, 34.0f, 35.0f, 36.0f};

    /*
    We can imagine this float A matrix as something like this

    A = {
        {1, 2, 3},
        {4, 5, 6},
        {7, 8, 9}
    } smilialry for B

    */

    int *device_arr_A;
    float *device_arr_B, *device_arr_C;
    cudaMalloc((void **)&device_arr_A, 9 * sizeof(int));
    cudaMalloc((void **)&device_arr_B, 36 * sizeof(float));
    cudaMalloc((void **)&device_arr_C, 3 * 3 * 6 * sizeof(float));

    cudaMemcpy(device_arr_A, A, 9 * sizeof(float), cudaMemcpyHostToDevice);
    cudaMemcpy(device_arr_B, B, 36 * sizeof(float), cudaMemcpyHostToDevice);

    dim3 grid(3, 3);
    dim3 block(6);
    kernel<<<grid, block>>>(device_arr_A, device_arr_B, device_arr_C, 6);

    cudaDeviceSynchronize();
    float C[3 * 3 * 6];
    cudaMemcpy(C, device_arr_C, 3 * 3 * 6 * sizeof(float), cudaMemcpyDeviceToHost);

    cudaFree(device_arr_A);
    cudaFree(device_arr_B);
    cudaFree(device_arr_C);

    for (int r = 0; r < 3; r++)
    {
        printf("t%d:\n", r);
        for (int c = 0; c < 3; c++)
        {
            printf("  col%d: [", c);
            for (int e = 0; e < 3; e++)
            {
                printf("%.1f ", C[r * 3 * 6 + c * 6 + e]);
            }
            printf("]\n");
        }
    }
}
#+END_SRC

That is our unit test for kernel launch in the cuda kernel. With that we were able to create a simple lookup. Depending upon the type of kenrel launch cuda lets us use the row and cols our our current block. And, inside of block we can have multiple threads, to prevent that multiple threads from writing into garbage data we create a boundry check like row < something .... Okay so,

Formula for getting current index is
#+BEGIN_SRC C
int index = (rows * 3) + cols; // (rows * width) + cols
// Think of this as a higher dimensional matrix converted into a flat array

/*

  A = {
     {1, 2, 3},
     {4, 5, 6},
     {7, 8, 9}
  }

  The flat version of this would be
  A = {1, 2, 3, 4, 5, 6}

,*/
#+END_SRC

So imagine we are on the position P(0, 0) row = 0, col = 0
index = (0 * 3) + 0 = 0
A[0] = 1 and so on. Simple math not something strict of a formula.

**** Our goal is simple lookup table for now
For now our goal is to understand how to create a simple lookup table. Inside of a transformer model training runs on batch and epoch so it will be hard for us to debug currently so what we can do is unit test be sure that things work then only add that unit.

Because value of A is row of B we can find value of B easily as well.

So for our matrix C we want it to be in the shape of seq_len x batch_size x d_model we want to write that flat srip of array to a 3d matrix.

so here.

#+BEGIN_SRC C
  C[row * gridDim.y * embed_dim + col * embed_dim + e] = val;
// C[row x batch_size x d_model + col x d_model + e]
#+END_SRC

In our example our batch_size = 3, seq_len = 3 and d_model = 6
#+BEGIN_SRC Python

Row 0: [....En] [...En][....] # This is a 3d matrix but in low level its a flat strip
rows*batch_size*d + cols*d + e

# Expaded shape (rows x batch_size x d_model)

#+END_SRC

We are adding that matrix B part inside the inner most cell by skipping the outer dimension I would say.
Lets think this 3d matrix as a flat array.

So basically we have. rows (rows) and batch_size = column and d_model as the value inside of the cell. In order to skip that we would rows * batch_size * d_model + cols * (d_model) + e
