#include "include/helper.h"
#include <cuda_runtime.h>
#include <iostream>
#include <memory>
#include <cstdio>
#include <chrono>

// Again my background is beginner here with little concept from C

// nvcc src/attention.cpp src/kernel/math.cu -o src/bin/attention
// ./src/bin/attention

// flat memory are efficient but the project for a beginner is so complicated that it will be fine just to get the model running.
// NVIDA cuda core kernel functions
// again optimising this might be even more difficult anyway lets just make it work.
extern "C" void positionalEmbeddings(float *out, int seq_len, int d_model);
extern "C" void lookup(int *x, float *embeddings, float *C, int d_model, int seq_len, int batch_size, int vocab_size);
class Embeddings
{

    // Positional ecnoding are fixed here generated by the sine and cosine function.
    // Token embeddings are learned in the back propagation first initillized randomly.

public:
    int d_model;
    int vocab_size;
    int seq_len;
    int batch_size;
    float *sinosudialEncoding;
    std::unique_ptr<Utility> utils = std::make_unique<Utility>();
    std::unique_ptr<Initializer> initilizer = std::make_unique<Initializer>();
    std::vector<std::vector<float>> tokenEmbeddings;

    // This is for debudding
    bool k = true;

    // Size of come commonly used types
    int sizeSinosudialEncoding;

    Embeddings(int d_model, int vocab_size, int seq_len, int batch_size)
    {
        this->d_model = d_model;
        this->vocab_size = vocab_size;
        this->seq_len = seq_len;
        this->batch_size = batch_size;

        // Allocate the memory on the host
        this->sinosudialEncoding = this->positionalEncoding(); // these are learned emebddings in modern day torch. I cannot handle much pain so I am doing this one.

        // this gets changed in the backpropagation
        this->tokenEmbeddings = initilizer->HeInit(this->vocab_size, this->d_model); // token embeddings

        // Defination of some memory size types
        sizeSinosudialEncoding = seq_len * d_model * sizeof(float);
    };

    ~Embeddings()
    {
        free(sinosudialEncoding);
    }

    float *positionalEncoding()
    {
        float *positionalEncodingOut = (float *)malloc(this->sizeSinosudialEncoding); // host memeory

        float *devicePositionalEncoding;
        cudaMalloc((void **)&devicePositionalEncoding, this->sizeSinosudialEncoding); // GPU memory

        positionalEmbeddings(devicePositionalEncoding, seq_len, d_model); // Kernal launch

        cudaMemcpy(positionalEncodingOut, // copy back
                   devicePositionalEncoding,
                   this->sizeSinosudialEncoding,
                   cudaMemcpyDeviceToHost);

        cudaFree(devicePositionalEncoding); // free gpu memory
        return positionalEncodingOut;
    }

    void forward(std::vector<std::vector<int>> x)
    {
        int batch_size = x[0].size(); // this is the batch_size
        int sizeFinalEmbeddings = seq_len * d_model * batch_size * sizeof(float);
        // x(seq_len, batch_size)
        int *hostX = utils->TwoDVectorToFlatMem(x);
        float *hostEmbeddings = utils->TwoDVectorToFlatMem(this->tokenEmbeddings);
        float *finalEmbeddings = (float *)malloc(sizeFinalEmbeddings);

        int *deviceX;
        float *deviceEmbeddings;
        float *deviceFinalEmbeddings;

        int sizeInputX = seq_len * batch_size * sizeof(int);
        int sizeTokenEmbeddings = seq_len * batch_size * d_model * sizeof(float);

        cudaMalloc((void **)&deviceX, sizeInputX);
        cudaMalloc((void **)&deviceEmbeddings, sizeTokenEmbeddings);
        cudaMalloc((void **)&deviceFinalEmbeddings, sizeFinalEmbeddings);

        cudaMemcpy(deviceX, hostX, sizeInputX, cudaMemcpyHostToDevice);
        cudaMemcpy(deviceEmbeddings, hostEmbeddings, sizeTokenEmbeddings, cudaMemcpyHostToDevice);

        // Kernel launch
        lookup(deviceX, deviceEmbeddings, deviceFinalEmbeddings, d_model, seq_len, batch_size, vocab_size);

        cudaMemcpy(finalEmbeddings, deviceFinalEmbeddings, sizeFinalEmbeddings, cudaMemcpyDeviceToHost);

        cudaFree(deviceX);
        cudaFree(deviceEmbeddings);
        cudaFree(deviceFinalEmbeddings);

        if (k == true)
        {

            std::cout << "Lookup result " << std::endl;
            utils->printFlatArray2D(hostEmbeddings, vocab_size, d_model);

            std::cout << "Input x " << std::endl;
            utils->printFlatArray2D(hostX, seq_len, batch_size);

            std::cout << "Look up result " << batch_size << std::endl;
            utils->printFlatArray3D(finalEmbeddings, seq_len, batch_size, d_model);

            std::cout << "seq_len=" << seq_len
                      << " batch_size=" << batch_size
                      << " d_model=" << d_model
                      << " vocab_size=" << vocab_size
                      << " sizeInputX=" << sizeInputX
                      << " sizeFinalEmbeddings=" << sizeFinalEmbeddings
                      << std::endl;
        }

        delete[] hostX; // we will assign this or reconvert back to a 2d shape
        delete[] hostEmbeddings;
        free(finalEmbeddings);

        k = false;
    }
};

class Attention
{
public:
    int &d_model;
    int &vocab_size;
    int &num_heads;
    int &seq_len;
    int &batch_size;
    std::unique_ptr<Embeddings> embeddings; // called in the constructor good.

    Attention(int &d_model, int &vocab_size, int &num_heads, int &seq_len, int &batch_size) : d_model(d_model), vocab_size(vocab_size), num_heads(num_heads), seq_len(seq_len), batch_size(batch_size)
    {
        this->embeddings = std::make_unique<Embeddings>(
            this->d_model,
            this->vocab_size,
            this->seq_len,
            this->batch_size);

        // Just to test and keep track of things
        std::cout << "d_model: " << d_model << std::endl;
        std::cout << "vocab_size: " << vocab_size << std::endl;
        std::cout << "seq_len: " << seq_len << std::endl;
        std::cout << "num_heads: " << num_heads << std::endl;
    };

public:
    void forward(std::vector<std::vector<int>> x)
    {

        if (d_model % num_heads != 0)
        {
            std::cout << "The number of heads must be perfectly divisible by dimesnion " << std::endl;
            return;
        }
        embeddings->forward(x);
    };
};

int main()
{
    cudaDeviceSynchronize();
    auto start = std::chrono::high_resolution_clock::now();

    int d_model = 16;
    int vocab_size; // that depends upon the data that you are passing.
    int num_heads = 2;
    int batch_size = 4;
    int seq_len = 8;
    int epoch = 12;
    bool drop_last = false;

    std::string path = "./src/data/chunk.txt";

    auto utils = std::make_unique<Utility>();

    auto textEncoderFile = std::make_unique<EncoderText>();

    textEncoderFile->loadTextChunk(path); // load that into char arr

    auto &charPool = textEncoderFile->getFileAsChar();
    auto helper = std::make_unique<Helper>(charPool);

    vocab_size = charPool.size();

    const std::vector<int> &encodedData = helper->getEncodedList();

    /* For something like attention we need heap allocation. */
    std::unique_ptr<Attention> attention = std::make_unique<Attention>(
        d_model,
        vocab_size,
        num_heads,
        seq_len,
        batch_size); // called once good.

    std::unique_ptr<DataLoader> dataLoader = std::make_unique<DataLoader>(batch_size, encodedData, seq_len, drop_last);

    std::unique_ptr<std::vector<IO>> dataList = dataLoader->getBatch();

    for (int i = 0; i < epoch; ++i)
    {
        for (auto &currentBatch : *dataList)
        {
            // so we have the x, and y here
            // My understanding is batches are SEQUENTIAL
            // but the procress within the batches are done in parallel.
            attention->forward(currentBatch.x);
        }
    }

    auto end = std::chrono::high_resolution_clock::now();
    cudaDeviceSynchronize(); // CPU is waiting for the GPU to finish
    std::chrono::duration<double, std::milli> duration = end - start;
    std::cout << "Total time (with sync overhead): " << duration.count() << " ms\n";

    return 0;
}