#include "include/helper.h"
#include <curand_kernel.h>
#include <cuda_runtime.h>
#include <iostream>
#include <memory>
#include <cstdio>
#include <chrono>

// Again my background is beginner here with little concept from C
// Transformer are complex neural network artitecture so I will focus on
// making the things right at first rather than micro level optimization
// The goal is to learn the underlying concept we can always bring the performace up later on.

// nvcc src/attention.cpp src/kernel/math.cu -o src/bin/attention
// ./src/bin/attention

// flat memory are efficient but the project for a beginner is so complicated that it will be fine just to get the model running.
// NVIDA cuda core kernel functions
// again optimising this might be even more difficult anyway lets just make it work.
extern "C" void positionalEmbeddings(float *out, int seq_len, int d_model);
extern "C" void lookup(int *x, float *embeddings, float *C, int d_model, int seq_len, int batch_size, int vocab_size);
extern "C" void addEmbeddings(float *lookedUpEmbeddings, float *sinosudialEncoding, float *C, int d_model, int seq_len, int batch_size);
extern "C" void KaimingInit(float *arr, curandState *state, int x, int y, unsigned long seed);
extern "C" void WeightedSum(float *x, float *w, float *b, float *c, int M, int K, int N);
extern "C" void multiHeadedAttention(int num_head, int head_dimension, float *ws, float *out, int batch_size, int d_model, int seq_len);
extern "C" void SwapNS(int num_head, int head_dimension, float *ws, float *out, int M, int K, int N, bool reverse);
extern "C" void TransposeKey(int num_heads, int head_dim, float *arr, float *out, int M, int N, int K, bool reverse);
extern "C" void QKmatmul(float *Q, float *Kt, float *out, int M, int N, int batch_size, int num_heads);
extern "C" void ScalerDvisionElem(float *arr, int batch, int n_head, int seq_len, int head_dim);
extern "C" void UpperTriangularMasking(float *arr, float val, int batch_size, int n_head, int seq_len);
extern "C" void softmax(float *arr, float *out, int N, int seq_len, int n_head, int batch_size);
extern "C" void QKVMatmulFinal(float *QK, float *V, float *out, int seq_len, int d_head, int n_head, int batch_size);
class Embeddings
{

    // Positional ecnoding are fixed here generated by the sine and cosine function.
    // Token embeddings are learned in the back propagation first initillized randomly.

public:
    int d_model;
    int vocab_size;
    int seq_len;
    int batch_size;
    float *sinosudialEncoding;
    std::unique_ptr<Utility> utils = std::make_unique<Utility>();
    std::unique_ptr<Initializer> initilizer = std::make_unique<Initializer>();
    std::vector<std::vector<float>> tokenEmbeddings;

    // This is for debudding
    bool k = true;

    Embeddings(int d_model, int vocab_size, int seq_len, int batch_size)
    {
        this->d_model = d_model;
        this->vocab_size = vocab_size;
        this->seq_len = seq_len;
        this->batch_size = batch_size;

        // Allocate the memory on the host
        this->sinosudialEncoding = this->positionalEncoding(); // these are learned emebddings in modern day torch. I cannot handle much pain so I am doing this one.

        // this gets changed in the backpropagation
        this->tokenEmbeddings = initilizer->HeInit(this->vocab_size, this->d_model); // token embeddings
    };

    ~Embeddings()
    {
        free(sinosudialEncoding);
    }

    float *positionalEncoding()
    {
        float *positionalEncodingOut = (float *)malloc(seq_len * d_model * sizeof(float)); // host memeory

        float *devicePositionalEncoding;
        cudaMalloc((void **)&devicePositionalEncoding, seq_len * d_model * sizeof(float)); // GPU memory

        positionalEmbeddings(devicePositionalEncoding, seq_len, d_model); // Kernal launch

        cudaMemcpy(positionalEncodingOut, // copy back
                   devicePositionalEncoding,
                   seq_len * d_model * sizeof(float),
                   cudaMemcpyDeviceToHost);

        cudaFree(devicePositionalEncoding); // free gpu memory
        return positionalEncodingOut;
    }

    float *forward(std::vector<std::vector<int>> x)
    {
        int batch_size = x[0].size(); // this is the batch_size
        int sizeFinalEmbeddings = seq_len * d_model * batch_size * sizeof(float);
        // x(seq_len, batch_size)
        int *hostX = utils->TwoDVectorToFlatMem(x);
        float *hostEmbeddings = utils->TwoDVectorToFlatMem(this->tokenEmbeddings);
        float *lookedUpEmbeddings = (float *)malloc(sizeFinalEmbeddings);

        int *deviceX;
        float *deviceEmbeddings;
        float *deviceFinalEmbeddings;

        int sizeInputX = seq_len * batch_size * sizeof(int);
        int sizeTokenEmbeddings = seq_len * batch_size * d_model * sizeof(float);

        cudaMalloc((void **)&deviceX, sizeInputX);
        cudaMalloc((void **)&deviceEmbeddings, sizeTokenEmbeddings);
        cudaMalloc((void **)&deviceFinalEmbeddings, sizeFinalEmbeddings);

        cudaMemcpy(deviceX, hostX, sizeInputX, cudaMemcpyHostToDevice);
        cudaMemcpy(deviceEmbeddings, hostEmbeddings, sizeTokenEmbeddings, cudaMemcpyHostToDevice);

        // kernel launch
        lookup(deviceX, deviceEmbeddings, deviceFinalEmbeddings, d_model, seq_len, batch_size, vocab_size);

        cudaMemcpy(lookedUpEmbeddings, deviceFinalEmbeddings, sizeFinalEmbeddings, cudaMemcpyDeviceToHost);

        cudaFree(deviceX);
        cudaFree(deviceEmbeddings);
        cudaFree(deviceFinalEmbeddings);

        float *addedEmbeddingsOut = (float *)malloc(sizeFinalEmbeddings); // this is the out.

        float *deviceSinosudialEncoding;
        float *deviceLookedUpEmbeddings; // Note:- it after we lookup in embddings from x
        float *deviceAddedEmbeddingsOut;

        cudaMalloc((void **)&deviceSinosudialEncoding, seq_len * d_model * sizeof(float));
        cudaMalloc((void **)&deviceAddedEmbeddingsOut, sizeFinalEmbeddings);
        cudaMalloc((void **)&deviceLookedUpEmbeddings, sizeFinalEmbeddings);

        // copy to gpu
        cudaMemcpy(deviceLookedUpEmbeddings, lookedUpEmbeddings, sizeFinalEmbeddings, cudaMemcpyHostToDevice);
        cudaMemcpy(deviceSinosudialEncoding, this->sinosudialEncoding, seq_len * d_model * sizeof(float), cudaMemcpyHostToDevice);

        addEmbeddings(deviceLookedUpEmbeddings, this->sinosudialEncoding, deviceAddedEmbeddingsOut, d_model, seq_len, batch_size);

        cudaMemcpy(addedEmbeddingsOut, deviceAddedEmbeddingsOut, sizeFinalEmbeddings, cudaMemcpyDeviceToHost);

        cudaFree(deviceSinosudialEncoding);
        cudaFree(deviceAddedEmbeddingsOut);
        cudaFree(deviceLookedUpEmbeddings);

        delete[] hostX; // we will assign this or reconvert back to a 2d shape
        delete[] hostEmbeddings;

        free(lookedUpEmbeddings);
        return addedEmbeddingsOut;
    }
};

bool dLinear = true;

class Linear
{
    float *ws = nullptr; // weighted sum
    float *weight = nullptr;
    float *bias = nullptr;
    float *x = nullptr;

    float *h_mha;

    float *d_x;
    float *d_w;
    float *d_b;
    float *d_out;

    int f_in;
    int f_out;
    int seq_len;
    int batch_size;
    std::unique_ptr<Utility> utils = std::make_unique<Utility>();

    float *mhead_out_host = nullptr; // output after multi head attention
    float *mhead_out_device;         // this is multi head attention out device
    float *device_hhead_in;          // copy to this from weighted sum

    float n_head;
    float head_dim;

    bool debug = true;

    float *deviceArrInTranspose;

public:
    Linear(int feature_in, int feature_out, int seq_len, int batch_size, int n_head)
    {
        this->seq_len = seq_len;
        this->batch_size = batch_size;
        this->f_in = feature_in;
        this->f_out = feature_out;
        this->n_head = n_head;
        this->head_dim = feature_out / n_head;
        this->LinearParams(feature_in, feature_out);

        // pre-allocate memroy in the constructor
        // because we need to flattern this, x (batch_size, seq_len, d_model)

        this->ws = (float *)malloc(seq_len * batch_size * f_out * sizeof(float));

        cudaMalloc((void **)&d_x, seq_len * batch_size * f_in * sizeof(float));
        cudaMalloc((void **)&d_w, f_in * f_out * sizeof(float)); // (M, K)
        cudaMalloc((void **)&d_b, f_out * sizeof(float));
        cudaMalloc((void **)&d_out, seq_len * batch_size * f_out * sizeof(float));

        // copy to the device, those allocated weight and biases.
        cudaMemcpy(d_w, weight, f_in * f_out * sizeof(float), cudaMemcpyHostToDevice);
        cudaMemcpy(d_b, bias, f_out * sizeof(float), cudaMemcpyHostToDevice);

        /// allocate the memory for multi headed attention Shape(B, T, num_heads, head_dim), JUST BTC when in
        cudaMalloc((void **)&device_hhead_in, seq_len * batch_size * f_out * sizeof(float)); // copy ws here

        this->mhead_out_host = (float *)malloc(seq_len * batch_size * n_head * head_dim * sizeof(float));

        cudaMalloc((void **)&mhead_out_device, seq_len * batch_size * n_head * head_dim * sizeof(float));

        // In order to transpose that Q,K,V and swap we need to allocate the memory in GDDR VRAM
        cudaMalloc((void **)&deviceArrInTranspose, batch_size * seq_len * n_head * head_dim * sizeof(float));
    }

    ~Linear()
    {
        (ws != nullptr ? free(ws) : void());
        (weight != nullptr ? free(weight) : void());
        (bias != nullptr ? free(bias) : void());

        (mhead_out_host != nullptr ? free(mhead_out_host) : void());

        cudaFree(d_x);
        cudaFree(d_w);
        cudaFree(d_b);
        cudaFree(d_out);

        cudaFree(deviceArrInTranspose);

        cudaFree(mhead_out_device);
    }

    void LinearParams(int fan_in, int fan_out)
    {
        weight = (float *)malloc(fan_in * fan_out * sizeof(float)); // these are out for both weight and biases.
        bias = (float *)malloc(fan_out * sizeof(float));

        float *device_weight;
        float *device_bias;
        curandState *d_state_weight;
        curandState *d_state_bias;

        cudaMalloc((void **)&device_weight, fan_in * fan_out * sizeof(float));
        cudaMalloc(&d_state_weight, fan_in * fan_out * sizeof(curandState));
        cudaMalloc(&d_state_bias, fan_out * sizeof(curandState));
        cudaMalloc((void **)&device_bias, fan_out * sizeof(float));

        // we need tow kernal launches here
        KaimingInit(device_weight, d_state_weight, fan_in, fan_out, 42);
        KaimingInit(device_bias, d_state_bias, 1, fan_out, 43);

        cudaMemcpy(weight, device_weight, fan_in * fan_out * sizeof(float), cudaMemcpyDeviceToHost);
        cudaMemcpy(bias, device_bias, fan_out * sizeof(float), cudaMemcpyDeviceToHost);

        cudaFree(device_weight);
        cudaFree(device_bias);
        cudaFree(d_state_weight);
        cudaFree(d_state_bias);

        // std::cout << "Weight" << std::endl;
        // utils->printFlatArray2D(weight, fan_in, fan_out);
        // std::cout << "Bias" << std::endl;
        // utils->printFlatArray2D(this->bias, fan_out, 1);
        // std::cout << "Fan in: " << fan_in << " Fan out: " << fan_out << std::endl;
    }

    float *getBias()
    {
        return this->bias;
    }

    float *getWeight()
    {
        return this->weight;
    }

    float *forward(float *val)
    {
        this->x = val;
        int m = batch_size * seq_len;

        cudaMemcpy(d_x, x, seq_len * batch_size * f_in * sizeof(float), cudaMemcpyHostToDevice);

        WeightedSum(d_x, d_w, d_b, d_out, m, f_in, f_out);

        cudaMemcpy(ws, d_out, seq_len * batch_size * f_out * sizeof(float), cudaMemcpyDeviceToHost);

        // std::cout << "Weight" << std::endl;
        // utils->printFlatArray2D(weight, f_in, f_out);

        // std::cout << "Bias" << std::endl;
        // utils->printFlatArray2D(bias, f_out, 1);

        // std::cout << "Weighted sum" << std::endl;
        // utils->printFlatArray3D(ws, seq_len, batch_size, f_out);

        return x;
    }

    float *reshapeHead() // make it have more dim so that effective computation can happen in parallel.
    {
        // copy that weighted sum into device so we can split it down.
        cudaMemcpy(device_hhead_in, ws, seq_len * batch_size * f_out * sizeof(float), cudaMemcpyHostToDevice);

        multiHeadedAttention(n_head, head_dim, device_hhead_in, mhead_out_device, batch_size, f_out, seq_len);

        cudaMemcpy(mhead_out_host, mhead_out_device, seq_len * batch_size * n_head * head_dim * sizeof(float), cudaMemcpyDeviceToHost);

        // Weighted sum looks healthy here.
        // if (dLinear)
        // {

        //     std::cout << "Weighted sum" << sizeof(device_hhead_in) << sizeof(ws) << std::endl;
        //     // utils->printFlatArray3D(ws, seq_len, batch_size, f_out, true);
        //     utils->printFlatArray3D(ws, batch_size, seq_len, f_out, true);

        //     std::cout << "Aafter reshape for multi headed attention" << std::endl;
        //     utils->print2DMatrixLastTwo(mhead_out_host, batch_size, n_head, seq_len);
        // }
        // dLinear = false;

        return mhead_out_host;
    }

    // without tranpose it would attend to seq_len which is just tokenized
    // if we swap it with n_head then it would attend to that which has values
    // inillized from he init that as inside of the embeddings.
    void swapHead(bool reverse)
    {
        // Before: Shape(batch_size, seq_len, n_head, d_head)
        // After: Shape(batch_size, n_head, seq_len, d_head)
        // std::cout << "Before transpose" << std::endl;
        // utils->print2DMatrixLastTwo(mhead_out_host, seq_len, n_head, head_dim);

        cudaMemcpy(deviceArrInTranspose, mhead_out_host, batch_size * seq_len * n_head * head_dim * sizeof(float), cudaMemcpyHostToDevice);

        SwapNS(n_head,
               head_dim,
               deviceArrInTranspose,
               mhead_out_device,
               batch_size,
               head_dim,
               seq_len,
               reverse);

        cudaMemcpy(mhead_out_host, mhead_out_device, seq_len * batch_size * n_head * head_dim * sizeof(float), cudaMemcpyDeviceToHost);

        // std::cout << "After transpose" << std::endl;
        // utils->print2DMatrixLastTwo(mhead_out_host, n_head, seq_len, head_dim);

        // very hard to think if in higher dimension, mathematicans cannot imagine higher dimension
        // Now our final resule shape would be Shape(batch_size, n_head, seq_len, d_head)
    }

    float *teansposeKeyForAttnScore()
    {

        // std::cout << "Before transpose" << std::endl;
        // utils->printFlarArray4D(mhead_out_host, batch_size, n_head, seq_len, head_dim);
        TransposeKey(
            n_head,
            head_dim,
            mhead_out_host, // it will replace that same variable variable
            mhead_out_device,
            batch_size,
            head_dim,
            seq_len,
            false);

        cudaMemcpy(mhead_out_host, mhead_out_device, seq_len * batch_size * n_head * head_dim * sizeof(float), cudaMemcpyDeviceToHost);

        // std::cout << "After transpose" << std::endl;
        // utils->printFlarArray4D(mhead_out_host, batch_size, n_head, seq_len, head_dim);

        return mhead_out_host;
    }
};

class Attention
{
public:
    int &d_model;
    int &vocab_size;
    int &num_heads;
    int &seq_len;
    int &batch_size;
    int head_dim;
    std::unique_ptr<Utility> utils = std::make_unique<Utility>();
    std::unique_ptr<Embeddings> embeddings; // called in the constructor good.
    std::unique_ptr<Linear> key;
    std::unique_ptr<Linear> query;
    std::unique_ptr<Linear> value;
    std::unique_ptr<Linear> outputProj;

    float *DeviceKt;
    float *DeviceQ;
    float *DeviceQKT;
    float *hostQKT = nullptr;

    bool debug = true;

    float *deviceQKTSqrtD;

    float *deviceSoftmaxOut;
    float *hostSoftmaxOut = nullptr;

    // QKV part allocation, Softmax(QK/sqrt(d_model)) V
    float *QKVOutHostOut = nullptr;
    float *QKVOutDeviceOut;
    float *deviceValue;

    Attention(int &d_model, int &vocab_size, int &num_heads, int &seq_len, int &batch_size) : d_model(d_model), vocab_size(vocab_size), num_heads(num_heads), seq_len(seq_len), batch_size(batch_size)
    {
        this->embeddings = std::make_unique<Embeddings>(
            this->d_model,
            this->vocab_size,
            this->seq_len,
            this->batch_size);

        // Lets seed Q,K,V
        key = std::make_unique<Linear>(d_model, d_model, seq_len, batch_size, num_heads);
        query = std::make_unique<Linear>(d_model, d_model, seq_len, batch_size, num_heads);
        value = std::make_unique<Linear>(d_model, d_model, seq_len, batch_size, num_heads);

        outputProj = std::make_unique<Linear>(d_model, d_model, seq_len, batch_size, num_heads);

        // Just to test and keep track of things
        std::cout << "d_model: " << d_model << std::endl;
        std::cout << "vocab_size: " << vocab_size << std::endl;
        std::cout << "seq_len: " << seq_len << std::endl;
        std::cout << "num_heads: " << num_heads << std::endl;

        this->head_dim = d_model / num_heads;

        // Q K^t matmul device and host allocation
        cudaMalloc((void **)&DeviceKt, batch_size * num_heads * head_dim * seq_len * sizeof(float));
        cudaMalloc((void **)&DeviceQ, batch_size * num_heads * head_dim * seq_len * sizeof(float));
        cudaMalloc((void **)&DeviceQKT, batch_size * num_heads * head_dim * seq_len * sizeof(float));

        // Q K^T Host
        hostQKT = (float *)malloc(batch_size * num_heads * head_dim * seq_len * sizeof(float));

        cudaMalloc((void **)&deviceQKTSqrtD, batch_size * num_heads * seq_len * seq_len * sizeof(float));

        // for softmax's
        this->hostSoftmaxOut = (float *)malloc(batch_size * num_heads * seq_len * seq_len * sizeof(float));
        // I do not deserve an internship so what, people who are doing this wont understand this so I am writing c++ to scare people off.
        cudaMalloc((void **)&deviceSoftmaxOut, batch_size * num_heads * seq_len * seq_len * sizeof(float));

        this->QKVOutHostOut = (float *)malloc(batch_size * num_heads * seq_len * head_dim * sizeof(float)); // (batch_size, n_head, T, d_head)
        cudaMalloc((void **)&QKVOutDeviceOut, batch_size * num_heads * seq_len * head_dim * sizeof(float));

        cudaMalloc((void **)&deviceValue, batch_size * num_heads * seq_len * head_dim * sizeof(float));
    };

    ~Attention()
    {
        cudaFree(DeviceKt);
        cudaFree(DeviceQ);
        cudaFree(DeviceQKT);

        cudaFree(deviceQKTSqrtD);

        (hostQKT != nullptr ? free(hostQKT) : void());

        (hostSoftmaxOut != nullptr ? free(hostSoftmaxOut) : void());

        (QKVOutHostOut != nullptr ? free(QKVOutHostOut) : void());

        cudaFree(deviceSoftmaxOut);
        cudaFree(deviceValue);
        cudaFree(QKVOutDeviceOut); // we could free in the individual method but if we never call them then its never free.
    }

public:
    // This method divides by sqrt of d_model so that atlast forward lgoic in this program looks readable to a normal human being.
    void scalerDvisionAcrossMat(float *QKt, int d_model)
    {
        // if (debug == true)
        // {
        //     std::cout << "Before dvision by the scaler" << std::endl;
        //     utils->printFlarArray4D(QKt, batch_size, num_heads, seq_len, seq_len);
        // }

        // copy that value from the pointer to device. dense looking C++ code to scare people. Just Kidiing!
        cudaMemcpy(deviceQKTSqrtD, QKt, batch_size * num_heads * seq_len * seq_len * sizeof(float), cudaMemcpyHostToDevice);

        // // (batch, n_head, seq_len, seq_len)
        ScalerDvisionElem(
            deviceQKTSqrtD,
            batch_size,
            num_heads,
            seq_len,
            head_dim);

        // copy back to QKT
        cudaMemcpy(QKt, deviceQKTSqrtD, batch_size * num_heads * seq_len * seq_len * sizeof(float), cudaMemcpyDeviceToHost);

        // if (debug == true)
        // {

        //     std::cout << "Afer division by the scaler " << std::endl;
        //     utils->printFlarArray4D(QKt, batch_size, num_heads, seq_len, seq_len);
        // }
    }

    void masking(float *arr, float val)
    {

        // copy to that deviceQKTSqrtD does not matter now. cudaDeviceSynchronize() waits until the GPU finishes. so use this as a memeory buffer. Later once we get the working result we can fix things like that.
        cudaMemcpy(deviceQKTSqrtD, arr, batch_size * num_heads * seq_len * seq_len * sizeof(float), cudaMemcpyHostToDevice);

        UpperTriangularMasking(deviceQKTSqrtD, val, batch_size, num_heads, seq_len);

        cudaError_t err = cudaGetLastError();
        // if (err != cudaSuccess)
        // {
        //     printf("Kernel error: %s\n", cudaGetErrorString(err));
        // }

        // if (debug == true)
        // {
        //     utils->print2DMatrixLastTwo(hostQKT, batch_size, num_heads, seq_len, "QKT Before Mask");
        // }
        cudaMemcpy(arr, deviceQKTSqrtD, batch_size * num_heads * seq_len * seq_len * sizeof(float), cudaMemcpyDeviceToHost); // we are copying to the same pointer does not matter if I am not wrong till this point.

        // if (debug == true)
        // {
        //     // std::cout << "QKT unmasked" << std::endl;
        //     // utils->printFlarArray4D(arr, batch_size, num_heads, seq_len, seq_len);

        //     utils->print2DMatrixLastTwo(arr, batch_size, num_heads, seq_len, "");
        // }
    }

    void QKVMatmul(float *QK, float *V)
    {
        // this is the pattern of learning we could have organized this in the wrapper but its fine here. if we did that then more number of paramaters in the wrapper.
        // deviceQKTSqrtD this as a BUFFER was well, forgive me I am just learning I will tewak and fix this weird naming.
        cudaMemcpy(deviceQKTSqrtD, QK, batch_size * num_heads * seq_len * seq_len * sizeof(float), cudaMemcpyHostToDevice); // QK to GDDR RAM
        cudaMemcpy(deviceValue, V, batch_size * num_heads * seq_len * head_dim * sizeof(float), cudaMemcpyHostToDevice);

        QKVMatmulFinal(deviceQKTSqrtD, deviceValue, QKVOutDeviceOut, seq_len, head_dim, num_heads, batch_size);

        cudaMemcpy(QKVOutHostOut, QKVOutDeviceOut, batch_size * num_heads * seq_len * head_dim * sizeof(float), cudaMemcpyDeviceToHost);

        // if (debug)
        // {
        //     std::cout << "Before matmul with QKV" << std::endl;
        //     utils->print2DMatrixLastTwo(QK, batch_size, num_heads, seq_len, "");

        //     std::cout << "After matmul with QKV" << std::endl;
        //     utils->print2DMatrixLastTwo(QKVOutHostOut, batch_size, num_heads, seq_len, "");

        //     std::cout << "Value data" << std::endl;
        //     utils->printFlarArray4D(V,  batch_size, num_heads, seq_len, head_dim);
        // }
    }

    void forward(std::vector<std::vector<int>> input)
    {

        if (d_model % num_heads != 0)
        {
            std::cout << "The number of heads must be perfectly divisible by dimesnion " << std::endl;
            return;
        }
        float *x = embeddings->forward(input);

        float *Q = query->forward(x); // We are doing a linear transformation here when we pass in the forward method.
        float *K = key->forward(x);
        float *V = value->forward(x);

        Q = query->reshapeHead(); // Shape(batch_size, T, n_head, head_dim)
        K = key->reshapeHead();
        V = value->reshapeHead(); // after swap  Shape(batch_size, n_head, T, d_head)

        float *s = key->teansposeKeyForAttnScore(); // Q K^T matmul
        cudaMemcpy(DeviceKt, s, seq_len * batch_size * num_heads * head_dim * sizeof(float), cudaMemcpyHostToDevice);
        cudaMemcpy(DeviceQ, s, seq_len * batch_size * num_heads * head_dim * sizeof(float), cudaMemcpyHostToDevice);

        QKmatmul(DeviceQ, DeviceKt, DeviceQKT, seq_len, head_dim, batch_size, num_heads); // S(1, 1, T, T)

        cudaMemcpy(hostQKT, DeviceQKT, batch_size * num_heads * seq_len * seq_len * sizeof(float), cudaMemcpyDeviceToHost);

        scalerDvisionAcrossMat(hostQKT, d_model); // sqrt(d_model)

        // if (debug == true)
        // {
        //     std::cout << "QKT unmasked" << std::endl;
        //       utils->print2DMatrixLastTwo(hostQKT, batch_size, num_heads, seq_len, "After sqrt(d_model)");
        // }

        // -1e9f
        masking(hostQKT, -1e9f);

        // if (debug == true)
        // {
        //     std::cout << "Before softmax " << std::endl;
        //     utils->print2DMatrixLastTwo(hostQKT, batch_size, num_heads, seq_len, "");
        // }

        // apply softmax part!
        cudaMemcpy(deviceQKTSqrtD, hostQKT, batch_size * num_heads * seq_len * seq_len * sizeof(float), cudaMemcpyHostToDevice);
        softmax(deviceQKTSqrtD, deviceSoftmaxOut, batch_size * num_heads * seq_len * seq_len, seq_len, num_heads, batch_size);

        // copy to host
        cudaMemcpy(hostSoftmaxOut, deviceSoftmaxOut, batch_size * num_heads * seq_len * seq_len * sizeof(float), cudaMemcpyDeviceToHost);

        // deviceQKTSqrtD Shape(batch_size, n_head, T, T)

        // if (debug == true)
        // {

        //     std::cout << "After softmax " << std::endl;
        //     utils->print2DMatrixLastTwo(hostSoftmaxOut, batch_size, num_heads, seq_len, "");
        // }

        // value Shape(batch_size, n_head, seq_len, d_head)
        // deviceQKTSqrtD Shape(batch_size, n_head, T, T)

        // Q K determines what to attend, and V determines where to attend.
        // we will write a basic matmul kernel nothing fancy later we can benchmarket and use tensor cores.

        QKVMatmul(hostSoftmaxOut, V); //  (batch_size, n_head, T, d_head)

        // Now we would want to bring back the shape to after the attention score.
        // Shape(batch, T, n_head, d_head) ..so we wap firt and second

        debug = false;
        free(x);
    };
};

int main()
{
    cudaDeviceSynchronize();
    auto start = std::chrono::high_resolution_clock::now();

    int d_model = 8;
    int vocab_size; // that depends upon the data that you are passing.
    int num_heads = 2;
    int batch_size = 4;
    int seq_len = 4;
    int epoch = 12;
    bool drop_last = false;

    std::string path = "./src/data/chunk.txt";

    auto utils = std::make_unique<Utility>();

    auto textEncoderFile = std::make_unique<EncoderText>();

    textEncoderFile->loadTextChunk(path); // load that into char arr

    auto &charPool = textEncoderFile->getFileAsChar();
    auto helper = std::make_unique<Helper>(charPool);

    vocab_size = charPool.size();

    const std::vector<int> &encodedData = helper->getEncodedList();

    /* For something like attention we need heap allocation. */
    // std::unique_ptr<Attention> attention = std::make_unique<Attention>(
    //     d_model,
    //     vocab_size,
    //     num_heads,
    //     seq_len,
    //     batch_size); // called once good.

    std::unique_ptr<DataLoader> dataLoader = std::make_unique<DataLoader>(batch_size, encodedData, seq_len, drop_last);

    std::unique_ptr<std::vector<IO>> dataList = dataLoader->getBatch();

    // for (int i = 0; i < epoch; ++i)
    // {
    //     for (auto &currentBatch : *dataList)
    //     {
    //         // so we have the x, and y here
    //         // My understanding is batches are SEQUENTIAL
    //         // but the procress within the batches are done in parallel.
    //         attention->forward(currentBatch.x);
    //     }
    // }

    float X[32] = {
        1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f,
        9.0f, 10.0f, 11.0f, 12.0f, 13.0f, 14.0f, 15.0f, 16.0f,
        17.0f, 18.0f, 19.0f, 20.0f, 21.0f, 22.0f, 23.0f, 24.0f,
        25.0f, 26.0f, 27.0f, 28.0f, 29.0f, 30.0f, 31.0f, 32.0f};
    auto linear1 = std::make_unique<Linear>(
        8,
        8,
        4,
        1,
        2 // n_heads
    );

    linear1->forward(X);
    linear1->reshapeHead();
    linear1->swapHead(false);
    linear1->teansposeKeyForAttnScore();

    auto end = std::chrono::high_resolution_clock::now();
    cudaDeviceSynchronize(); // CPU is waiting for the GPU to finish
    std::chrono::duration<double, std::milli> duration = end - start;
    std::cout << "Total time (with sync overhead): " << duration.count() << " ms\n";

    return 0;
}