#include "include/helper.h"
#include <cuda_runtime.h>
#include <iostream>
#include <memory>
#include <cstdio>
#include <chrono>

// Again my background is beginner here with little concept from C

// nvcc src/attention.cpp src/kernel/math.cu -o src/bin/attention
// ./src/bin/attention

// NVIDA cuda core kernel functions
extern "C" void positionalEmbeddings(float *out, int seq_len, int d_model);
class Embeddings
{

    // Positional ecnoding are fixed here generated by the sine and cosine function.
    // Token embeddings are learned in the back propagation first initillized randomly.

public:
    int d_model;
    int vocab_size;
    int seq_len;
    std::unique_ptr<Utility> utils = std::make_unique<Utility>();
    std::unique_ptr<Initializer> initilizer = std::make_unique<Initializer>();

    Embeddings(int d_model, int vocab_size, int seq_len)
    {
        this->d_model = d_model;
        this->vocab_size = vocab_size;
        this->seq_len = seq_len;
    };

    float *positionalEncoding()
    {
        int shape = d_model * seq_len;
        float *positionalEncodingOut = (float *)malloc(shape * sizeof(float));

        float *devicePositionalEncoding;
        cudaMalloc((void **)&devicePositionalEncoding, shape * sizeof(float));

        positionalEmbeddings(devicePositionalEncoding, seq_len, d_model);

        cudaMemcpy(positionalEncodingOut,
                   devicePositionalEncoding,
                   shape * sizeof(float),
                   cudaMemcpyDeviceToHost);

        cudaFree(devicePositionalEncoding);
        return positionalEncodingOut;
    }

    /* I am not sure if we want to make positional encoding and other arrays flat
    because the memory strip on hardware level is flat itself and GPU on parallel handels things in flat way. */
    void generateEmbeddings(std::vector<int> batch)
    {
        // Allocate the memory on the host
        int shape = d_model * seq_len;

        // this gets changed in the backpropagation
        std::vector<std::vector<float>> tokenEmbeddings = initilizer->HeInit(this->vocab_size, this->d_model); // token embeddings

        float *sinosudialEncoding = this->positionalEncoding(); // in moden torch this also gets chaged but are using sinosudial encoding for simplicity here.
        // This lnag itself is difficult so I wont comment abuut the concept much to keep it clearn, I have notes on note.org


        // Now inorder to get the array from token embeddings i.e rows the runtime complexity if O(1)
        /* Lookup happens in the parallel */


        free(sinosudialEncoding);
        // We have the token emb with some numbers, and their row is basically our encoded id (based on position or whatever). We fetch those rows according to the seq_len and add those two.
    }
};

class Attention
{
public:
    int &d_model;
    int &vocab_size;
    int &num_heads;
    int &seq_len;
    std::unique_ptr<Embeddings> embeddings;

    Attention(int &d_model, int &vocab_size, int &num_heads, int &seq_len) : d_model(d_model), vocab_size(vocab_size), num_heads(num_heads), seq_len(seq_len)
    {
        this->embeddings = std::make_unique<Embeddings>(
            this->d_model,
            this->vocab_size,
            this->seq_len);

        // Just to test and keep track of things
        std::cout << "d_model: " << d_model << std::endl;
        std::cout << "vocab_size: " << vocab_size << std::endl;
        std::cout << "seq_len: " << seq_len << std::endl;
        std::cout << "num_heads: " << num_heads << std::endl;
    };

public:
    void forward(std::vector<int> batch)
    {

        if (d_model % num_heads != 0)
        {
            std::cout << "The number of heads must be perfectly divisible by dimesnion " << std::endl;
            return;
        }

        embeddings->generateEmbeddings(batch);
    };
};

int main()
{
    cudaDeviceSynchronize();
    auto start = std::chrono::high_resolution_clock::now();

    int d_model = 128;
    int vocab_size; // that depends upon the data that you are passing.
    int num_heads = 64;
    int batch_size = 33;
    int seq_len = 4;
    bool drop_last = false;

    std::string path = "./src/data/chunk.txt";

    auto utils = std::make_unique<Utility>();

    auto textEncoderFile = std::make_unique<EncoderText>();

    textEncoderFile->loadTextChunk(path); // load that into char arr

    auto &charPool = textEncoderFile->getFileAsChar();
    auto helper = std::make_unique<Helper>(charPool);

    vocab_size = charPool.size();

    const std::vector<int> &encodedData = helper->getEncodedList();

    /* For something like attention we need heap allocation. */
    std::unique_ptr<Attention> attention = std::make_unique<Attention>(
        d_model,
        vocab_size,
        num_heads,
        seq_len);

    std::unique_ptr<DataLoader> dataLoader = std::make_unique<DataLoader>(batch_size, encodedData, drop_last);

    std::vector<std::vector<int>> getBatch = dataLoader->getBatch();

    // utils->Print2DVector(getBatch);

    auto end = std::chrono::high_resolution_clock::now();

    cudaDeviceSynchronize(); // CPU is waiting for the GPU to finish
    std::chrono::duration<double, std::milli> duration = end - start;
    std::cout << "Total time (with sync overhead): " << duration.count() << " ms\n";

    return 0;
}